@startuml
skinparam dpi 200
skinparam sequenceMessageAlign center
skinparam monochrome true
skinparam sequenceParticipantBorderThickness 2
skinparam sequenceArrowThickness 2

actor "Scheduler" as scheduler
participant "MemberScheduler\n@Component" as controller
participant "MemberService\n@Service" as service
participant "MemberMapper\n@Mapper" as mapper
database "Database" as db

scheduler -> controller : deleteOutMembers()
activate controller

controller -> service : deleteOutMembers()
activate service

service -> mapper : deleteOutMembers()
activate mapper

mapper -> db : DELETE FROM members\nWHERE is_out='Y' AND\nedit_date < DATE_ADD(NOW(), INTERVAL -3 month)
activate db
db --> mapper : int (affected rows)
deactivate db

mapper --> service : int
deactivate mapper

service --> controller : int
deactivate service

controller --> scheduler : void
deactivate controller

@enduml